//! Niri background blur integration.

use crate::config::AppearanceConfig;
use std::path::PathBuf;
use std::process::Command;
use tracing::{debug, warn};

const HAMR_BLUR_INCLUDE: &str = "hamr/blur.kdl";

pub(crate) fn sync_blur_config(appearance: &AppearanceConfig) {
    if std::env::var("NIRI_SOCKET").is_err() {
        return;
    }

    let Some(niri_dir) = niri_config_dir() else {
        warn!("Unable to resolve Niri config directory for blur integration");
        return;
    };

    let hamr_dir = niri_dir.join("hamr");
    let blur_path = hamr_dir.join("blur.kdl");
    if let Err(e) = std::fs::create_dir_all(&hamr_dir) {
        warn!("Failed to create {:?}: {}", hamr_dir, e);
        return;
    }

    let content = if appearance.background_blur {
        blur_layer_rule(appearance)
    } else {
        String::new()
    };

    let file_changed = write_if_changed(&blur_path, &content);
    let include_changed = ensure_niri_include(&niri_dir);
    if file_changed || include_changed {
        reload_niri_config();
    }
}

fn niri_config_dir() -> Option<PathBuf> {
    let config_home = std::env::var("XDG_CONFIG_HOME")
        .map(PathBuf::from)
        .ok()
        .or_else(|| dirs::home_dir().map(|home| home.join(".config")))?;
    Some(config_home.join("niri"))
}

fn write_if_changed(path: &std::path::Path, content: &str) -> bool {
    if std::fs::read_to_string(path).is_ok_and(|existing| existing == content) {
        return false;
    }

    match std::fs::write(path, content) {
        Ok(()) => true,
        Err(e) => {
            warn!("Failed to write {:?}: {}", path, e);
            false
        }
    }
}

fn ensure_niri_include(niri_dir: &std::path::Path) -> bool {
    let config_path = niri_dir.join("config.kdl");
    let include_line = format!("include \"{HAMR_BLUR_INCLUDE}\"");

    let Ok(existing) = std::fs::read_to_string(&config_path) else {
        return false;
    };

    if existing.contains(&include_line) {
        return false;
    }

    let needs_newline = !existing.is_empty() && !existing.ends_with('\n');
    let mut updated = existing;
    if needs_newline {
        updated.push('\n');
    }
    updated.push_str(&include_line);
    updated.push('\n');

    match std::fs::write(&config_path, updated) {
        Ok(()) => true,
        Err(e) => {
            warn!(
                "Failed to add Hamr blur include to {:?}: {}",
                config_path, e
            );
            false
        }
    }
}

fn reload_niri_config() {
    match Command::new("niri")
        .args(["msg", "action", "load-config-file"])
        .output()
    {
        Ok(output) if output.status.success() => {
            debug!("Reloaded Niri config after Hamr blur update");
        }
        Ok(output) => {
            warn!(
                "Failed to reload Niri config after Hamr blur update: status={}",
                output.status
            );
        }
        Err(e) => {
            warn!(
                "Failed to run niri config reload after Hamr blur update: {}",
                e
            );
        }
    }
}

fn blur_layer_rule(appearance: &AppearanceConfig) -> String {
    let passes = appearance.background_blur_passes.clamp(1, 8);
    let offset = appearance.background_blur_offset.clamp(1.0, 12.0);
    let saturation = appearance.background_blur_saturation.clamp(0.0, 2.0);

    format!(
        r#"// Generated by Hamr. Configure from /settings -> Appearance.
blur {{
    passes {passes}
    offset {offset:.1}
    saturation {saturation:.2}
}}

layer-rule {{
    match namespace="^hamr$"

    background-effect {{
        blur true
        xray false
    }}
}}
"#
    )
}
